[Log]
# valid levels are 'error', 'warning', 'info', 'verbose', 'debug'
level = 'info' 

[Listen]
# see https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-models-ng for available languages
language = 'en-US_Multimedia'

[See]
# camera resolution is width x height
cameraResolution = [1280, 720]

# if true, flips the camera image vertically
verticalFlip = false

# if true, flips the camera image horizontally
horizontalFlip = false

[Shine.NeoPixel]
# NeoPixels must be connected to GPIO10, GPIO12, GPIO18 or GPIO21 to work.
# GPIO18 is the standard pin, but sound must be disabled to use GPIO18.
# 
# To disable sound, edit /boot/config.txt and change:
#   dtparam=audio=on
# to:
#   dtparam=audio=off
# and then reboot.
# 
# See https://pinout.xyz for a complete listing of RPi pins.
# See https://learn.adafruit.com/neopixels-on-raspberry-pi/raspberry-pi-wiring
# for more information about using NeoPixels with RPi.
gpioPin = 18 # GPIO18 / Physical pin 12

# if true, uses the GRB (instead of RGB) color format
grbFormat = false

[Shine.CommonAnode]
redPin = 19   # GPIO19 / Physical pin 35
greenPin = 13 # GPIO13 / Physical pin 33
bluePin = 12  # GPIO12 / Physical pin 32

[Speak]
# see https://cloud.ibm.com/docs/text-to-speech?topic=text-to-speech-voices for available voices
voice = 'en-US_MichaelV3Voice'

# use 'aplay -l' to see a list of playback devices
device = 'plughw:0,0' # plugged-in USB card 0, device 0

[Wave]
servoPin = 7 # GPIO7 / Physical Pin 26